apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node21824github
  janus-idp.io/tekton: node21824github
  backstage.io/kubernetes-id: node21824github
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node21824github
resources:
- deployment.yaml
- route.yaml
- service.yaml
